# 该配置本来就是clash的节点配置

proxies:
  # id 1
  - name: vless-ws
    server: ""
    port: 80
    type: vless
    uuid: 5be9524f-ed57-4957-9644-00be2a1e8e83      # 修改这里
    network: ws
    udp: false
    tls: false
    client-fingerprint: chrome
    skip-cert-verify: true
    ws-opts:
      path: /?ed=2048                               # 修改这里
      headers:
        Host: vless.username.workers.dev            # 修改这里

  # id 2
  - name: vless-ws-tls
    server: ""
    port: 443
    type: vless
    uuid: 0195cf0e-1b62-7ecf-892e-3bc510e47915      # 修改这里
    network: ws
    udp: false
    tls: true                                       # 这个跟前面那个不同
    servername: vless.pages.dev                     # 修改这里
    client-fingerprint: chrome
    skip-cert-verify: true
    ws-opts:
      path: /?ed=2048                               # 修改这里
      headers:
        Host: vless.pages.dev                       # 修改这里

  # id 3：clash核心不支持trojan-ws，只支持trojan-ws-tls
  - name: trojan-ws-tls
    server: ""
    port: 443
    type: trojan
    password: 0195cf0d-f3f8-72f4-80dc-5385831c8dfa  # 修改这里
    network: ws
    udp: false
    sni: trojan.pages.dev                           # 修改这里
    client-fingerprint: chrome
    skip-cert-verify: true
    ws-opts:
      path: /                                       # 修改这里
      headers:
        Host: trojan.pages.dev                      # 修改这里

  # id 4
  - name: shadowsocks-v2ray_plugin-nTLS
    server: ""
    port: 80
    type: ss
    cipher: none
    password: none                                  # 这个值，修改无效
    udp: false
    plugin: v2ray-plugin
    plugin-opts:
      mode: websocket
      # path: /127.0.0.1-443/SSSIG_value            # 修改这里-PROXYIP（格式：/IP-端口、/PROXYIP/SSSIG)
      path: /127.0.0.1-443                          # 修改这里-PROXYIP（格式：/IP-端口、/PROXYIP/SSSIG)
      host: ss-v2ray.pages.dev                      # 修改这里
      tls: false                                    # 选择性修改这里，确定是否开启TLS，使用什么端口
      mux: false

  # id 5
  - name: shadowsocks-v2ray_plugin-TLS
    server: ""
    port: 443
    type: ss
    cipher: none
    password: none                                  # 这个值，修改无效
    udp: false
    plugin: v2ray-plugin
    plugin-opts:
      mode: websocket
      path: /127.0.0.1-443                          # 修改这里-PROXYIP（格式：/IP-端口、/PROXYIP/SSSIG)
      host: ss-v2ray.pages.dev                      # 修改这里
      tls: true                                     # 选择性修改这里，确定是否开启TLS，使用什么端口
      mux: false

# 后面可以继续模仿前面的配置添加
# 注意：同一个脚本，在这里推荐写一个，如果同脚本配置多个节点，使用singbox、clash会导致所有的节点无法使用，需要等待一段时间后，才能使用。
