# 该配置本来就是clash的节点配置

proxies:

# id 1：vless+ws
- type: vless
  name: vless+ws
  server: ""
  port: 80
  uuid: 5be9524f-ed57-4957-9644-00be2a1e8e83     # 修改这里
  network: ws
  tls: false
  udp: false
  # servername: vless.abc.workers.dev            # 修改这里
  client-fingerprint: chrome
  skip-cert-verify: true
  ws-opts:
    path: /?ed=2048                              # 修改这里
    headers:
      Host: vless.abc.workers.dev                # 修改这里

# id 2：vless+ws+tls
- type: vless
  name: vless+ws+tls
  server: ""
  port: 443
  uuid: 0195cf0e-1b62-7ecf-892e-3bc510e47915     # 修改这里
  network: ws
  tls: true
  udp: false
  servername: vless.pages.dev                    # 修改这里
  client-fingerprint: chrome
  skip-cert-verify: true
  ws-opts:
    path: /?ed=2048                              # 修改这里
    headers:
      Host: vless.pages.dev                      # 修改这里

# id 3：trojan+ws+tls
# clash核心不支持trojan+ws，只支持trojan+ws+tls
- type: trojan
  name: trojan+ws+tls
  server: ""
  port: 443
  password: 0195cf0d-f3f8-72f4-80dc-5385831c8dfa # 修改这里
  network: ws
  udp: false
  sni: trojan.pages.dev                          # 修改这里
  client-fingerprint: chrome
  skip-cert-verify: true
  ws-opts:
    path: /                                      # 修改这里
    headers:
      Host: trojan.pages.dev                     # 修改这里

# id 4：ss+v2ray-plugin+TLS
- type: ss
  name: ss-v2ray
  server: ""
  port: 443
  cipher: none
  password: 0195cf0d-d50f-7589-8141-b0e0477c9425 # 修改这里
  udp: false
  plugin: v2ray-plugin
  plugin-opts:
    mode: websocket
    path: /127.0.0.1-443                         # 修改这里-PROXYIP（格式：/IP-端口）
    host: ss-v2ray.pages.dev                     # 修改这里
    tls: true
    mux: false

# 后面可以继续模仿前面的配置添加
